### ISSUE TITLE
vars/RedHat.yml: htop is not present in RH-supported repositories

### ISSUE THREAD

**Issue by matsimon** [adfinis-sygroup/ansible-role-console#2]
Enforcing the presence of htop require the EPEL repository to be enabled. However neither does RH support EPEL packages, nor is it always even recommended to enable EPEL in certain situations. (i.e. on RHVH and vdsm version are known examples to me).

Either dropping the requirement for htop OR having a knob/variable that allows enabling/disabling EPEL for RHEL-derived distributions and defaulting to false if on RHEL would be quite nice.

**Comment by karras** [comment]
We should drop it in the RHEL vars and define specific ones for CentOS6/7.
